# Generated by Django 3.2.18 on 2023-03-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_user_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/default_profile_oq6ujj', upload_to='images/'),
        ),
    ]
